networks:
  queue-practice:
    name: queue-practice
    driver: bridge

services:
  queue-practice-cli:
    container_name: queue-practice-cli
    networks:
      - queue-practice
    build:
      context: ../../
      dockerfile: ./.deployment/docker/php-cli/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    depends_on:
      - rabbitmq
    volumes:
      - ./../../:/var/www/queue-practice

  queue-practice-worker:
    container_name: queue-practice-worker
    networks:
      - queue-practice
    build:
      context: ../../
      dockerfile: ./.deployment/docker/php-worker/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    depends_on:
      - rabbitmq
    volumes:
      - ./../../:/var/www/queue-practice
      - ./supervisor/conf.d:/etc/supervisor/conf.d

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.3-management-alpine
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_MANAGEMENT_PORT}:15672
    networks:
      - queue-practice
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local
